# Generated by Django 3.0.5 on 2020-04-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('casting_time', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=100)),
                ('targets', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('saving_throw', models.CharField(max_length=100)),
                ('spell_resistance', models.CharField(max_length=100)),
                ('short_desc', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Spell')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.School')),
            ],
        ),
    ]
