# Generated by Django 3.0.5 on 2020-04-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200407_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classspells',
            old_name='pc_class',
            new_name='pcclass_id',
        ),
        migrations.RenameField(
            model_name='classspells',
            old_name='name',
            new_name='spell_id',
        ),
    ]
