# Generated by Django 3.0.5 on 2020-04-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200407_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='school',
            new_name='school_id',
        ),
    ]
