# Generated by Django 3.0.5 on 2020-04-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200407_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classspells',
            old_name='pcclass_id',
            new_name='pc_class',
        ),
        migrations.RenameField(
            model_name='classspells',
            old_name='spell_id',
            new_name='spell',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='school_id',
            new_name='school',
        ),
    ]
